
-- qst 1 
CONNECT system/1234 ;

DESCRIBE DICT ;
SELECT * FROM DICT ;

-- qst2
DESCRIBE ALL_TAB_COLUMNS;
SELECT COMMENTS FROM DICT WHERE TABLE_NAME='ALL_TAB_COLUMNS';

DESCRIBE USER_USERS ;
SELECT COMMENTS FROM DICT WHERE TABLE_NAME='USER_USERS';

DESCRIBE ALL_CONSTRAINTS ;
SELECT COMMENTS FROM DICT WHERE TABLE_NAME='ALL_CONSTRAINTS';

DESCRIBE USER_TAB_PRIVS ;
SELECT COMMENTS FROM DICT WHERE TABLE_NAME='USER_TAB_PRIVS';

-- qst3
SELECT USER FROM DUAL;

-- qst4
DESCRIBE USER_TAB_COLUMNS;
DESCRIBE ALL_TAB_COLUMNS;

-- qst5
