
CONNECT DBAIOT/tifoura123A ;

-- Création de la table USER
CREATE TABLE USERS (
    IDUSER NUMBER PRIMARY KEY,
    LASTNAME VARCHAR(20) NOT NULL,
    FIRSTNAME VARCHAR(20),
    EMAIL VARCHAR(40) UNIQUE
);

-- Création de la table SERVICE
CREATE TABLE SERVICE (
    IDSERVICE NUMBER PRIMARY KEY,
    NAME VARCHAR(20),
    SERVICETYPE VARCHAR(20)
);

-- Création de la table THING
CREATE TABLE THING (
    MAC CHAR(17) PRIMARY KEY ,
    IDUSER NUMBER REFERENCES USERS(IDUSER) ON DELETE CASCADE,
    THINGTYPE VARCHAR(20),
    PARAM VARCHAR(20)
);

-- Création de la table SUBSCRIBE
CREATE TABLE SUBSCRIBE (
    IDUSER NUMBER REFERENCES USERS(IDUSER) ON DELETE CASCADE,
    IDSERVICE NUMBER REFERENCES SERVICE(IDSERVICE) ON DELETE CASCADE,
    PRIMARY KEY (IDUSER, IDSERVICE)
);


-- Ajout de la colonne ADRESSUSER
ALTER TABLE USERS 
ADD ADRESSUSER VARCHAR(30);

-- Ajout de la contrainte NOT NULL sur ADRESSUSER
ALTER TABLE USERS 
MODIFY ADRESSUSER VARCHAR(30) NOT NULL;

-- Ajout de la contrainte NOT NULL sur LASTNAME 
ALTER TABLE USERS 
MODIFY LASTNAME VARCHAR(20) NOT NULL;

--Agrandir la taill de ADRESSUSER
ALTER TABLE USERS 
MODIFY ADRESSUSER VARCHAR(80);

--Reduire la taille de ADRESSUSER
ALTER TABLE USERS 
MODIFY ADRESSUSER VARCHAR(40);

--Renomer ADRESSUSER et verification
ALTER TABLE USERS 
RENAME COLUMN ADRESSUSER TO ADRUSER;
DESC USERS; 

--Suppression de ADRUSER et confirmation
ALTER TABLE USERS
DROP COLUMN ADRUSER;
DESC USERS; 

--Repondre au besoin 
ALTER TABLE SUBSCRIBE 
ADD START_DATE DATE;
ALTER TABLE SUBSCRIBE 
ADD END_DATE DATE;
DESC SUBSCRIBE ;








